### ISSUE TITLE
Flat Rate for function calculateFarePrice not correct per the test

### ISSUE THREAD

**Issue by rsleiberin** [learn-co-curriculum/phase-1-functions-lab#10]
### Canvas Link

https://learning.flatironschool.com/courses/4992/assignments/165587?module_item_id=357180

### Concern

The function calculateFarePrice should return 32 ((2000 feet - 400 free feet)*.02) not 25 based on the instructions.

### Suggested Changes

Include in the instructions that the flat fare after 2000 for calculateFarePrice should be "25" or change the test value to "32".

**Comment by graciemcguire** [comment]
Hey @rsleiberin, thanks for raising this issue!

Part of the way we developed these labs was for students to get comfortable reading tests.
In the ReadMe on lines 75-76 it says _"Then Scuber charges a flat fare for a distance over 2000 feet and under 2500 feet."_
From this note we know that there is definitely going to be a flat fare. So if we go check our tests, on lines 54-56 we have  the following test:

```js
it('charges 25 dollars for a distance over 2000 feet', function() {
      expect(calculatesFarePrice(50, 58)).to.equal(25);
    });
```

Our goal here is for students to practice their test-reading skills while learning to write functions! 😄 

I am going to close this issue for now, but if you feel I have closed it in error, please feel free to open a new issue.
Thanks, and happy coding!
